apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  # root password: rootpassword123
  mysql-root-password: cm9vdHBhc3N3b3JkMTIz
  # app user password: apppassword123
  mysql-app-password: YXBwcGFzc3dvcmQxMjM=
