apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: default
data:
  init.sql: |
    -- Create application database
    CREATE DATABASE IF NOT EXISTS myapp;
    
    -- Create application user
    CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'apppassword123';
    
    -- Grant privileges to application user
    GRANT ALL PRIVILEGES ON myapp.* TO 'appuser'@'%';
    GRANT SELECT, INSERT, UPDATE, DELETE ON myapp.* TO 'appuser'@'%';
    
    -- Create a sample table for testing
    USE myapp;
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50) NOT NULL UNIQUE,
        email VARCHAR(100) NOT NULL UNIQUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Insert sample data
    INSERT IGNORE INTO users (username, email) VALUES 
    ('admin', 'admin@example.com'),
    ('testuser', 'test@example.com'),
    ('demo', 'demo@example.com');
    
    -- Flush privileges
    FLUSH PRIVILEGES;
